name: ProMCCore
main: com.promcteam.engine.NexEngine
version: %PROJECT_VERSION%
description: ProRPG Core plugin
authors: [Travja, goflish]
softdepend: [Vault, WorldGuard, MythicMobs]
api-version: 1.14
load: STARTUP