name: ${project.name}
main: mc.promcteam.engine.NexEngine
version: ${project.version}
description: ProRPG Core plugin
authors: [ Travja, goflish ]
softdepend: [ Vault, WorldGuard, MythicMobs ]
api-version: 1.14
load: STARTUP
libraries: [ mysql:mysql-connector-java:8.0.27, org.apache.commons:commons-lang3:3.12.0 ]