name: ProMCCore
main: su.nexmedia.engine.NexEngine
version: 2.0.6
description: ProRPG Core plugin
authors: [Travja, goflish]
softdepend: [Vault, WorldGuard, MythicMobs]
api-version: 1.14
load: STARTUP